bash create_slides.sh data-science-osm-wikidata "Data Science with OSM and Wikidata"
bash create_slides.sh ogr-presentation "OGR"
bash create_slides.sh osm-data-science "OpenStreetMap Data Science"
bash create_slides.sh osm-predict-economic-indicators "Predict Economic Indicators with OSM"
bash create_slides.sh scalable-geospatial-data-science "Scalable Geospatial Data Science"
bash create_slides.sh structured-web "Structured Web"
bash create_slides.sh wikidata-mayors "Wikidata Mayors"
bash create_slides.sh wikidata-openstreetmap "Wikidata OpenStreetMap"
